### ISSUE TITLE
Big Red Bar

### ISSUE THREAD

**Issue by ALASKAWARRIORS** [AlessioMR/matrix_glow#1]
Love the theme, I was wondering if there's any way to remove the big red bar in the code window? 
![Big Red Bar](https://user-images.githubusercontent.com/78138886/131241555-9cfe565f-7e1f-496f-9584-4e05358f319e.png)

**Comment by AlessioMR** [comment]
This is the margin line. You can turn it off in RStudio under Tools -> Global Options... -> Code -> Display -> Show margin. I always have it off so I didn't notice it when designing the skin. Thank you for letting me know, I will adjust the theme.

**Comment by ALASKAWARRIORS** [comment]
Thanks for the tip!
